# Generated by Django 4.2.16 on 2024-10-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=15)),
                ('year', models.IntegerField(max_length=4)),
                ('accident_reported', models.BooleanField(default=False)),
            ],
        ),
    ]
